eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8769

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    api-a:
      path: /beta-auth/**
      serviceId: beta-auth
    api-b:
      path: /beta-service/**
      serviceId: beta-service


