spring:
  application:
      name: beta-auth
  profiles:
    active: dev

logging:
  config: classpath:logback-dev.xml

swagger:
  basePackage:  com.shizijie.beta
  title:  beta的api文档
  description:  简单优雅的restfun风格
  version:  1.0