eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 1   #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
#    lease-expiration-duration-in-seconds: 2    #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉
  client:
    register-with-eureka: false   #fasle将不会启动注册操作
    registry-fetch-interval-seconds: 30   #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    fetch-registry: false   #是否需要去检索寻找服务，默认是true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.104:33306/beta?characterEncoding=utf8
    username: root
    password: 123456
  #redis
  redis:
    database: 0
    host: 192.168.1.104
    password: foobared
    port: 36379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1


# mybatis配置
mybatis:
  typeAliasesPackage: com.shizijie.beta
  mapper-locations: classpath:com/shizijie/beta/**/*.xml

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



