spring:
  application:
      name: beta-auth
  profiles:
    active: dev

logging:
  config: classpath:logback-dev.xml
  level: info

swagger:
  basePackage:  com.shizijie.beta
  title:  beta的api文档
  description:  简单优雅的restfun风格
  version:  1.0

mybatis:
  config-location: classpath:mybatis-config.xml

filter:
  passUrl: /user/login
  onOff: false
  sessionTimeOut: 1800

snowFlake:
  redis:
    open: true
    key: beta