eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

spring:
  application:
    name: service-beta
  # mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33306/beta?characterEncoding=utf8
    username: root
    password: 123456
  #redis
  redis:
    database: 0
    host: 127.0.0.1
    password: foobared
    port: 56379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1


# mybatis配置
mybatis:
  typeAliasesPackage: com.shizijie.beta
  mapper-locations: classpath:com/shizijie/beta/**/*.xml

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



