eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8765

spring:
  application:
    name: service-beta
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:53306/beta?characterEncoding=utf8
    username: root
    password: 123456

# mybatis配置
mybatis:
  typeAliasesPackage: com.shizijie.beta
  mapper-locations: classpath:com/shizijie/beta/**/*.xml

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


